// <auto-generated />
using System;
using MetanoiaCoreAPI.Infa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace test_project2.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200926032743_Database")]
    partial class Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("MetanoiaCoreAPI.AdminUser.AdminUserDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("MetanoiaCoreAPI.AppUser.AppUserDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Gender")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("varchar(200)");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("PsychologyCausesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PsychologyEffectsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationshipStatus")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("varchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("appuser");
                });
#pragma warning restore 612, 618
        }
    }
}
